# ─────────────────────────────────────────────
#  Project Configuration
# ─────────────────────────────────────────────

# ── Shared paths (used across multiple modules) ──
paths:
  ds_csv    : "/content/drive/MyDrive/PFE_data_CRAN/data_approach_1_split_miner_2/prefix_alignments_dataset.csv"
  pnml_path : "/content/drive/MyDrive/PFE_data_CRAN/data_approach_1_split_miner_2/petri_net_model/split_miner_sm2_eps0.1_eta0.4.pnml"
  xes_path  : "/content/drive/MyDrive/PFE_data_CRAN/data_approach_1_split_miner_2/xes_conf_metric.xes"
  project_root: "/content/online-conformance-checking/Petri_net_RL_approach"

# ── Activity key ──
activity_key: "concept:name"

# ─────────────────────────────────────────────
#  Module: dataset.py
# ─────────────────────────────────────────────
dataset:
  ds_csv:       ${paths.ds_csv}
  pnml_path:    ${paths.pnml_path}
  xes_path:     ${paths.xes_path}
  activity_key: ${activity_key}

# ─────────────────────────────────────────────
#  Module: ppo_evaluate.py
# ─────────────────────────────────────────────
evaluate:
  ds_csv:           ${paths.ds_csv}
  pnml_path:        ${paths.pnml_path}
  ppo_pt:           "ppo_pt.pth"
  model_phase1_out: "model_phase1_out.pth"

# ─────────────────────────────────────────────
#  Module: ppo_train.py
# ─────────────────────────────────────────────
phase2:
  ds_csv:           ${paths.ds_csv}
  pnml_path:        ${paths.pnml_path}
  model_phase1_out: "model_phase1_out.pth"
  ppo_out:          "ppo_pt.pth"

  # ── PPO hyper-parameters ──
  hyperparameters:
    gamma:      0.99
    lam:        0.95
    clip:       0.2
    ent_coef:   0.01
    vf_coef:    0.5
    lr:         3.0e-4
    max_grad:   0.5
 
  # ── Training schedule ──
  schedule:
    ppo_epochs: 5
    episodes:   30
    batch_size: 8
    max_steps:  60
    k_train:    598 # this is not used , selection of traces is based on fitness subsets 

phase1:
  ds_csv:           ${paths.ds_csv}
  pnml_path:        ${paths.pnml_path} 
  model_phase1_checkpoint: "model_phase1_checkpoint.pth"    
  model_phase1_out: "model_phase1_out.pth"

  # ── Imitation hyper-parameters ──
  hyperparameters:
    lr:         3.0e-4
    max_grad:   0.5
    w_label:    1.0   # cross-entropy weight for activity-label head
 
  # ── Training schedule ──
  schedule:
    phase1_epochs: 10
    batch_size:    8
    max_steps:     150
    k_train:       598 # this is not used , selection of traces is based on fitness subsets 